# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs: 
   - job: Build
     displayName: Build steps
     steps:
     - task: CopyFiles@2
       displayName: 'Copy Files to artifact staging directory'
       inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)'
         Contents: '*.zip'
         TargetFolder: $(Build.ArtifactStagingDirectory)
     - upload: $(Build.ArtifactStagingDirectory)
       artifact: drop
   - job: Get the build version 
     displayName: Get the build version from trigger file
     steps:
      - task: CmdLine@2
        inputs:
          script: |
            CURRENT_VER=`cat Trigger_File.txt | grep "Version" |  | cut -d  ":" -f2`
                         echo $CURRENT_VER >/home/vsts/work/1/a/Ver_file
                         major=`echo $CURRENT_VER | cut -d "." -f1`
                  		   minor=`echo $CURRENT_VER | cut -d "." -f2`
                  		   patch=`echo $CURRENT_VER | cut -d "." -f3`
                         newpatch=$(expr "$patch" + 1)
                  		   newversion=`echo $major.$minor.$newpatch`
                  		   echo $newversion
                         pwd
                  		   sed \'s/"Version" : "\'$CURRENT_VER\'"/"Version" : "\'$newversion\'"/\' Trigger_File.txt > NewTrigger_File.txt
                  		   mv NewTrigger_File.txt Trigger_File.txt
                  		   echo "Execute Completed"
                  		   git add Trigger_File.txt
                  		   git commit -m "version $newversion"
                  		   git push
     


       



