# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Codecheckout
  displayName: Checkour the repo 
  jobs:
    - job: checkoutcode
      displayName: checkout the source-repo
      steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo 'stage  code checkout'
              cat $(trigger_file)
              
- stage: SourceVersion 
  displayName: read the trigger to get version
  jobs:
    - job: readtrigger
      displayName: read the file
      steps:
         - task: Bash@3
           inputs:
             targetType: 'inline'
             script: |
              while IFS= read -r line
              do
                 version=`echo $line |cut -d "," -f2| grep "Version" | cut -d ":" -f2 |sed 's/"//g'`
                 echo $version
                 major=`echo $version |cut -d "." -f1`
                 minor=`echo $version |cut -d "." -f2`
                 patch=`echo $version |cut -d "." -f3`
                 newpatch=$(expr "$patch" + 1)
                 newversion=`echo $major.$minor.$newpatch`
                 echo $newversion $version
                 line1=`echo $line |sed "s/{$version}/{$newversion}/g"`
                 echo $line1
              done < $(trigger_file)

- stage: checkinformatica
  displayName: check the informatica connection
  jobs:
    - job: checkdevinfo
      displayName: check informativa dev connection
      pool: server
      steps:
        - task: InvokeRESTAPI@1
          inputs:
               connectionType: 'connectedServiceName'
               serviceConnection: 'iicsqa'
               method: 'POST'
               waitForCompletion: 'false'



      
     
         


       



