# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Codecheckout
  displayName: Checkour the repo 
  jobs:
    - job: checkoutcode
      displayName: checkout the source-repo
      steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo 'stage  code checkout'
- stage: SourceVersion 
  displayName: read the trigger to get version
  jobs:
    - job: readtrigger
      displayName: read the file
      steps:
         - task: Bash@3
           inputs:
             filePath: '$(System.DefaultWorkingDirectory).'
             filename: readTriggerFile.sh
      
     
         


       



